name: Parallel Cross-Browser Selenium Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      url:
        description: 'Test URL'
        required: false
        default: 'https://way2automation.com/way2auto_jquery/index.php'

jobs:
  test-linux-browsers:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: ['chrome']
    env:
      TEST_URL: ${{ github.event.inputs.url || 'https://way2automation.com/way2auto_jquery/index.php' }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Browsers
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable firefox

      - name: Run Selenium Tests with Pytest
        run: pytest --browser ${{ matrix.browser }} --url ${{ env.TEST_URL }} --html=reports/report.html

      - name: Upload HTML Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: html-report
          path: reports/report.html